// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proojekat.Models;

namespace proojekat.Migrations
{
    [DbContext(typeof(OOADContext))]
    partial class OOADContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("proojekat.Models.Gost", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime");

                    b.Property<string>("Prezime");

                    b.HasKey("ID");

                    b.ToTable("Gost");
                });

            modelBuilder.Entity("proojekat.Models.Ponuda", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("ETCS");

                    b.Property<string>("Naziv");

                    b.HasKey("ID");

                    b.ToTable("Ponuda");
                });

            modelBuilder.Entity("proojekat.Models.Rezervacija", b =>
                {
                    b.Property<int>("RezervacijaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GostId");

                    b.Property<int>("Ocjena");

                    b.Property<int>("PonudaId");

                    b.HasKey("RezervacijaId");

                    b.HasIndex("GostId");

                    b.HasIndex("PonudaId");

                    b.ToTable("Rezervacija");
                });

            modelBuilder.Entity("proojekat.Models.Rezervacija", b =>
                {
                    b.HasOne("proojekat.Models.Gost", "Gost")
                        .WithMany("Rezervacija")
                        .HasForeignKey("GostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("proojekat.Models.Ponuda", "Ponuda")
                        .WithMany("Rezervacija")
                        .HasForeignKey("PonudaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
